export const elektronik = [
  "computerskærm",
  "computer",
  "mobiltelefon",
  "tablet",
  "laptop",
  "skærm",
  "iphone",
  "android",
  "airpod",
  "høretelefon",
  "router",
  "3d-printer",
  "tastatur",
  "mus",
  "webkamera",
  "headsets",
  "monitor",
  "scanner",
  "iPad",
  "gaming skærm",
  "grafikkort",
  "cpu",
  "ram",
  "motherboard",
  "harddisk",
  "ssd",
  "stationær computer",
  "bærbar computer",
  "arbejdscomputer",
  "android tablet",
  "android telefon",
  "fastnettelefon",
  "betalingsterminal",
  "tv",
  "infoskærm",
  "højtaler",
  "mikrofon",
  "podcast mikrofon",
  "vaskemaskine",
  "tørretumbler",
  "opvaskemaskine",
  "køleskab",
  "ovn",
  "komfur",
  "mikrobølgeovn",
  "kaffemaskine",
  "kølefryseskab",
  "skabsfryser",
  "kummefryser",
  "emhætte",
  "støvsuger",
  "robotstøvsuger",
  "ledningsfri støvsuger",
  "espressomaskine",
  "kapselmaskine",
  "stempelkande",
  "gasgril",
  "kulgril",
  "elkedel",
  "blender",
  "airfryer",
  "toaster",
  "strygejern",
  "droner",
  "elcykel",
];

export const moelber = [
  "kontorstol",
  "sofaer",
  "senge",
  "stole",
  "bord",
  "bænke",
  "skjole",
  "stegepande",
  "gryde",
];

const haven = ["havemøbel", "plæneklipper"];

export const keywords = [...elektronik, ...moelber, ...haven];
